CREATE TABLE IF NOT EXISTS mpa (
                                   id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   name VARCHAR(10)
);

CREATE TABLE IF NOT EXISTS genre (
                                     id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name VARCHAR(50)
);
CREATE TABLE IF NOT EXISTS films(
                                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    name VARCHAR(100),
                                    description VARCHAR(1000),
                                    release_date DATE,
                                    duration INTEGER,
                                    id_mpa INTEGER REFERENCES mpa (id)
);

CREATE TABLE IF NOT EXISTS genre_films (
                                           id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           id_film INTEGER REFERENCES films (id),
                                           id_genre INTEGER REFERENCES genre (id)
);

CREATE TABLE IF NOT EXISTS users (
                                     id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     email VARCHAR(100),
                                     login VARCHAR(100),
                                     name VARCHAR(100),
                                     birthday DATE
);

CREATE TABLE IF NOT EXISTS likes_films (
                                           id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           id_films INTEGER REFERENCES films (id),
                                           id_user INTEGER REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS friends (
                                       id INTEGER GENERATED  BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       id_user INTEGER REFERENCES users (id),
                                       id_friends INTEGER,
                                       friendship_status BOOLEAN
);

INSERT INTO mpa (name)
VALUES ('G'),
       ('PG'),
       ('PG-13'),
       ('R'),
       ('NC-17');

INSERT INTO genre (name)
VALUES ('Комедия'),
       ('Драма'),
       ('Мультфильм'),
       ('Триллер'),
       ('Документальный'),
       ('Боевик');